[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Servi /accordo/ come pagina statica (eccezione al catch-all SPA)
[[redirects]]
  from   = "/accordo/*"
  to     = "/accordo/:splat"
  status = 200

# (opzionale ma comodo) URL senza slash → aggiunge slash
[[redirects]]
  from   = "/accordo"
  to     = "/accordo/"
  status = 301

# Catch-all per la tua SPA
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# Evita che Google indicizzi la pagina del contratto
[[headers]]
  for = "/accordo/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
