[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Serve i file statici nella cartella /accordo/
[[redirects]]
  from   = "/accordo/*"
  to     = "/accordo/:splat"
  status = 200

# Redireziona /accordo → /accordo/ (per caricare index.html)
[[redirects]]
  from   = "/accordo"
  to     = "/accordo/"
  status = 301

# Catch-all per la tua SPA React/Vite
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# Evita indicizzazione della pagina accordo
[[headers]]
  for = "/accordo/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
